/**
 * The encoder itself, against real ffmpeg.
 *
 * Opt-in like the renderer's tests, and for the same kind of reason: these need a binary the repo does not
 * carry, and vendoring ~78 MB of ffmpeg to assert a crop was not worth it. Everything that can be checked
 * without it -- the filtergraph, the argument order, the spec envelope -- is offline in
 * tests/unit/video_clip.test.ts.
 *
 *   brew install ffmpeg
 *   NOCT_LIVE=1 npx vitest run tests/live/clip.live.test.ts
 *
 * The source is generated by ffmpeg rather than committed, so there is no fixture video in the repo and
 * the test can pick an awkward aspect ratio on purpose -- landscape is the case `cover` has to handle.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { clip } from '../../src/video/clip.js';
import { available, probe, run } from '../../src/video/ffmpeg.js';
import { clipSpecSchema, ENCODE, REEL } from '../../src/video/spec.js';

const live = Boolean(process.env.NOCT_LIVE);
let dir = '';
let source = '';

/** 8 seconds of 1920x1080 test pattern with a tone, which is the landscape case `cover` must crop. */
async function makeSource(path: string): Promise<void> {
  await run('ffmpeg', [
    '-hide_banner', '-nostdin', '-y',
    '-f', 'lavfi', '-i', 'testsrc=size=1920x1080:rate=30:duration=8',
    '-f', 'lavfi', '-i', 'sine=frequency=440:duration=8',
    '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest',
    path,
  ]);
}

beforeAll(async () => {
  if (!live) return;
  if (!(await available())) throw new Error('NOCT_LIVE is set but ffmpeg is not on PATH');
  dir = await mkdtemp(join(tmpdir(), 'noct-clip-live-'));
  source = join(dir, 'source.mp4');
  await makeSource(source);
}, 120_000);

afterAll(async () => {
  if (dir) await rm(dir, { recursive: true, force: true });
});

const spec = (over: Record<string, unknown> = {}) => clipSpecSchema.parse(over);

describe.runIf(live)('clip', () => {
  it('crops landscape footage to a full-screen vertical reel', async () => {
    const out = join(dir, 'cover.mp4');
    const result = await clip({ ...spec(), input: source, output: out, length: 4, cover: null });
    expect(result.meta.width).toBe(REEL.w);
    expect(result.meta.height).toBe(REEL.h);
    expect(result.meta.seconds).toBeCloseTo(4, 0);
    expect(result.meta.vcodec).toBe('h264');
    // A reel with no audio track reads as broken on some surfaces, so there is always one.
    expect(result.meta.acodec).toBe('aac');
    expect(result.meta.fps).toBeCloseTo(ENCODE.fps, 0);
    // Landscape source, vertical output: no letterbox warning, because it was cropped and not padded.
    expect(result.warnings).toEqual([]);
  }, 180_000);

  it('starts where --start says', async () => {
    const out = join(dir, 'seek.mp4');
    const result = await clip({ ...spec({ start: 5 }), input: source, output: out, cover: null });
    // 8s source, starting at 5 -- so about 3 left, not 8.
    expect(result.meta.seconds).toBeGreaterThan(2);
    expect(result.meta.seconds).toBeLessThan(4);
  }, 180_000);

  it('refuses a start past the end of the source instead of writing an empty file', async () => {
    await expect(clip({ ...spec({ start: 99 }), input: source, output: join(dir, 'nope.mp4'), cover: null }))
      .rejects.toThrow(/past the end/);
  }, 60_000);

  it('rejects an output too short to publish rather than letting the Graph API do it', async () => {
    // 3s is Instagram's floor. A 1s clip encodes perfectly well and then fails on upload.
    await expect(clip({ ...spec({ start: 0 }), input: source, output: join(dir, 'short.mp4'), length: 1, cover: null }))
      .rejects.toThrow(/at least 3s/);
  }, 120_000);

  it('burns the title in without changing the geometry', async () => {
    const out = join(dir, 'titled.mp4');
    const result = await clip({
      ...spec({ title: 'SACRO', sub: 'Basement / Friday', titleSeconds: 2 }),
      input: source, output: out, length: 4, cover: join(dir, 'titled-cover.jpg'),
    });
    expect(result.meta.width).toBe(REEL.w);
    expect(result.meta.height).toBe(REEL.h);
    expect(result.coverPath).not.toBeNull();
    const cover = await probe(result.coverPath!);
    // The cover comes from the output, so it is cropped and titled the same way the video is.
    expect(cover.width).toBe(REEL.w);
    expect(cover.height).toBe(REEL.h);
  }, 240_000);

  it('writes a silent track for --mute rather than no track at all', async () => {
    const out = join(dir, 'muted.mp4');
    const result = await clip({ ...spec({ mute: true }), input: source, output: out, length: 4, cover: null });
    expect(result.meta.acodec).toBe('aac');
    expect(result.warnings).toEqual([]);
  }, 180_000);

  it('letterboxes with contain, and says so', async () => {
    const out = join(dir, 'contain.mp4');
    const result = await clip({ ...spec({ framing: 'contain' }), input: source, output: out, length: 4, cover: null });
    expect(result.meta.width).toBe(REEL.w);
    expect(result.meta.height).toBe(REEL.h);
  }, 180_000);

  it('fills the frame with a blurred copy for blur', async () => {
    const out = join(dir, 'blur.mp4');
    const result = await clip({ ...spec({ framing: 'blur' }), input: source, output: out, length: 4, cover: null });
    expect(result.meta.width).toBe(REEL.w);
    expect(result.meta.height).toBe(REEL.h);
  }, 240_000);
});
