-- NOCT 0006: New York venue seed — the curated half of venue resolution (resolve_venue in 0002_core.sql).
-- ~40 venues + rooms + TBA sentinels, their families (room -> complex), label variants each source uses, and the
-- source ids we know. Everything here re-applies safely: venues upsert on slug, aliases on alias_norm, external
-- ids on (source_key, source_id). Re-seeding overwrites curated columns but keeps geocodes and `verified` learned
-- elsewhere. Priors (space_types, typical_genres, vibe_priors, underground_prior) are reasonable defaults for the
-- rules engine, not measurements; codes follow the taxonomy in docs/GENRE_VIBE.md / 0004.
--
-- Provenance rules: address/postal only where known (verified = true only where a human confirmed it: Nowadays,
-- BASEMENT), website/instagram only where known, capacity only where widely published (noted 'approx'),
-- phone_policy only where verified — none are in this build, so it stays null and `notes` says so.
--
-- Apply BEFORE the first ingest. upsert_listing() creates a provisional venue ('<name>-<hash6>', needs_review)
-- for any label it cannot resolve and learns that label as an alias; if ingest ran first, this seed still applies
-- (slugs differ, aliases upsert) but the learned alias keeps winning over the curated name, so listings stay on
-- the provisional row. One-time merge: point the alias at the curated row and move the listings —
--   update venue_alias set venue_id = <curated> where venue_id = <provisional>;
--   update listing set venue_id = <curated> where venue_id = <provisional>;  then refresh_event() per event and drop the row.
-- tests/unit/seed_venues.test.ts exercises exactly this for 'LoHi'.
set search_path = public, extensions;

------------------------------------------------------------------------------
-- 1. Venues (parents are linked in step 2, so the order of rows does not matter)
------------------------------------------------------------------------------
insert into venue (slug, name, kind, address, postal_code, borough, neighborhood, lat, lng, website, instagram, ra_url, dice_url,
                   capacity, space_types, outdoor, underground_prior, typical_genres, vibe_priors, verified, needs_review, notes)
select s.slug, s.name, s.kind, s.address, s.postal_code, s.borough, s.neighborhood, s.lat::double precision, s.lng::double precision,
       s.website, s.instagram, s.ra_url, s.dice_url, s.capacity::int, coalesce(s.space_types::text[], '{}'), s.outdoor::boolean,
       s.underground_prior::smallint, coalesce(s.typical_genres::text[], '{}'), coalesce(s.vibe_priors::text[], '{}'),
       coalesce(s.verified::boolean, false), coalesce(s.needs_review::boolean, false), s.notes
from (values
  -- slug, name, kind, address, postal, borough, neighborhood, lat, lng, website, instagram, ra_url, dice_url,
  -- capacity, space_types, outdoor, underground_prior, typical_genres, vibe_priors, verified, needs_review, notes

  -- Queens -------------------------------------------------------------------------------------------------------
  ('nowadays', 'Nowadays', 'venue', '56-06 Cooper Ave, Ridgewood, NY 11385', '11385', 'Queens', 'Ridgewood', 40.692462, -73.901536,
   'https://nowadays.nyc', 'nowadaysnyc', 'https://ra.co/clubs/105873', null,
   600, '{club,outdoor_yard}', false, 4, '{house.deep,house.disco,techno.dub,leftfield.experimental}', '{sound_system_focus,underground,local_crews}', true, false,
   'Address verified (prototype + RA venue record; coords from RA). Capacity approx. Calendar and RSVP live on RA (club 105873). A no-photos dancefloor policy is widely reported but was NOT verified here: phone_policy left null.'),
  ('nowadays-yard', 'Nowadays Yard', 'outdoor', '56-06 Cooper Ave, Ridgewood, NY 11385', '11385', 'Queens', 'Ridgewood', null, null,
   null, null, null, null, null, '{outdoor_yard}', true, 4, '{house.deep,house.disco}', '{outdoor_yard,sunny_day_party}', false, false,
   'Outdoor yard at Nowadays (Mister Sunday, day parties). Room of nowadays.'),
  ('basement', 'BASEMENT', 'venue', '52-19 Flushing Ave, Maspeth, NY 11378', '11378', 'Queens', 'Maspeth', null, null,
   'https://basementny.net', null, 'https://ra.co/clubs/165976', null,
   null, '{basement,warehouse,club}', false, 5, '{techno.peak,techno.hard,techno.dub,techno.minimal}', '{dark_warehouse,sweaty_basement,underground,international_headliner}', true, false,
   'Address verified (prototype). Shares the Knockdown Center site but is a different operator: kept as its own venue, NOT a room of knockdown-center. House rules page describes a no-photo policy; not verified here, phone_policy null.'),
  ('knockdown-center', 'Knockdown Center', 'complex', '52-19 Flushing Ave, Maspeth, NY 11378', '11378', 'Queens', 'Maspeth', null, null,
   'https://knockdown.center', null, 'https://ra.co/clubs/69401', null,
   3000, '{warehouse,art_space,outdoor_yard}', false, 3, '{house.deep,techno.peak,techno.hard,bass.club}', '{dark_warehouse,big_room_club,festival_scale_lineup}', false, false,
   'Capacity approx (~3,000 incl. the Ruins). Address widely published, not human-verified here. Own site sits behind a Vercel challenge; listings come via RA / DICE / TicketWeb.'),
  ('knockdown-ruins', 'Ruins at Knockdown Center', 'outdoor', '52-19 Flushing Ave, Maspeth, NY 11378', '11378', 'Queens', 'Maspeth', null, null,
   null, null, null, null, null, '{outdoor_yard}', true, 3, '{house.deep,techno.peak}', '{outdoor_yard,day_into_night}', false, false,
   'Outdoor courtyard of Knockdown Center. Room of knockdown-center.'),
  ('moma-ps1', 'MoMA PS1', 'venue', '22-25 Jackson Ave, Long Island City, NY 11101', '11101', 'Queens', 'Long Island City', null, null,
   'https://www.momaps1.org', 'momaps1', 'https://ra.co/clubs/2495', null,
   null, '{art_space,outdoor_yard}', true, 2, '{open.eclectic,leftfield.experimental,bass.club,house.deep}', '{sunny_day_party,art_space,outdoor_yard,all_ages}', false, false,
   'Warm Up summer series in the courtyard. Address widely published, not human-verified here.'),
  ('h0l0', 'H0L0', 'venue', '1090 Wyckoff Ave, Ridgewood, NY 11385', '11385', 'Queens', 'Ridgewood', null, null,
   null, null, 'https://ra.co/clubs/137550', null,
   null, '{club,bar}', false, 5, '{techno.hard,electro.electro,bass.club,leftfield.experimental}', '{intimate_room,underground,local_crews}', false, false,
   'Address widely published, not human-verified here.'),
  ('trans-pecos', 'Trans-Pecos', 'venue', '915 Wyckoff Ave, Ridgewood, NY 11385', '11385', 'Queens', 'Ridgewood', null, null,
   null, null, null, null,
   null, '{art_space,outdoor_yard}', false, 5, '{leftfield.experimental,techno.hard,live.indie_electronic,bass.club}', '{art_space,local_crews,underground,all_ages}', false, false,
   'Address widely published, not human-verified here. Backyard used in summer.'),
  ('tv-eye', 'TV Eye', 'venue', '1647 Weirfield St, Ridgewood, NY 11385', '11385', 'Queens', 'Ridgewood', null, null,
   'https://tveyenyc.com', 'tveyenyc', null, null,
   null, '{club,bar,outdoor_yard}', false, 4, '{live.indie_electronic,electro.postpunk_newwave,techno.peak,open.eclectic}', '{local_crews,intimate_room}', false, false,
   'Tickets via See Tickets US (wl.seetickets.us). Mostly live; DJ nights late. Address widely published, not human-verified here.'),

  -- Brooklyn: complexes and their rooms --------------------------------------------------------------------------
  ('avant-gardner', 'Avant Gardner', 'complex', '140 Stewart Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'East Williamsburg', null, null,
   null, null, 'https://ra.co/clubs/105938', 'https://dice.fm/venue/pacha-new-york-6dvb7',
   null, '{warehouse,club,outdoor_yard}', false, 1, '{techno.peak,house.tech,trance.prog,dubstep.us_bass}', '{big_room_club,mainstream_club,international_headliner,pricey}', false, false,
   'Operating as Pacha New York in 2026: RA club 286414 and DICE venue pacha-new-york-6dvb7 both map to this family. Both official domains (avant-gardner.com, brooklynmirage.com) were down on 2026-09-13, so no website. Rooms carry the capacities.'),
  ('brooklyn-mirage', 'Brooklyn Mirage', 'outdoor', '140 Stewart Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'East Williamsburg', null, null,
   null, null, null, null, 6000, '{outdoor_yard}', true, 1, '{techno.peak,house.tech,trance.prog}', '{outdoor_yard,big_room_club,mainstream_club}', false, false,
   'Seasonal open-air room of avant-gardner. Capacity approx.'),
  ('the-great-hall', 'The Great Hall', 'room', '140 Stewart Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'East Williamsburg', null, null,
   null, null, null, null, 3000, '{warehouse}', false, 1, '{techno.peak,house.tech}', '{big_room_club,dark_warehouse}', false, false,
   'Indoor main room of avant-gardner. Capacity approx.'),
  ('kings-hall', 'Kings Hall', 'room', '140 Stewart Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'East Williamsburg', null, null,
   null, null, null, null, 1000, '{club}', false, 1, '{techno.peak,house.tech}', '{big_room_club}', false, false,
   'Smaller indoor room of avant-gardner. Capacity approx.'),
  ('elsewhere', 'Elsewhere', 'complex', '599 Johnson Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   'https://www.elsewhere.club', 'elsewherespace', null, null,
   null, '{club,rooftop}', false, 2, '{house.tech,techno.peak,live.indie_electronic,open.eclectic}', '{big_room_club,rooftop}', false, false,
   'Address from the venue site (events.json). Rooms: Hall, Zone One, Rooftop, Loft; "Full Venue" shows resolve to this row. Tickets on Eventbrite.'),
  ('elsewhere-hall', 'Elsewhere Hall', 'room', '599 Johnson Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null, 700, '{club}', false, 2, '{house.tech,techno.peak,live.indie_electronic}', '{big_room_club}', false, false,
   'Main room ("The Hall") of elsewhere. Capacity approx.'),
  ('elsewhere-zone-one', 'Elsewhere Zone One', 'room', '599 Johnson Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null, 200, '{club}', false, 3, '{house.deep,techno.dub,bass.club}', '{intimate_room,local_crews}', false, false,
   'Small room of elsewhere. Capacity approx.'),
  ('elsewhere-rooftop', 'Elsewhere Rooftop', 'outdoor', '599 Johnson Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null, null, '{rooftop}', true, 2, '{house.disco,house.deep,open.eclectic}', '{rooftop,sunny_day_party}', false, false,
   'Seasonal rooftop of elsewhere.'),
  ('elsewhere-loft', 'Elsewhere Loft', 'room', '599 Johnson Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null, null, '{bar}', false, 2, '{open.eclectic,live.indie_electronic}', '{intimate_room}', false, false,
   'Bar/loft room of elsewhere.'),
  ('public-records', 'Public Records', 'venue', '233 Butler St, Brooklyn, NY 11217', '11217', 'Brooklyn', 'Gowanus', 40.6822605, -73.9863775,
   'https://publicrecords.nyc', 'publicrecordsnyc', null, 'https://dice.fm/venue/public-records-w2qg',
   null, '{club,bar}', false, 4, '{house.deep,techno.dub,leftfield.downtempo,jazz.balearic_global}', '{sound_system_focus,listening_focus,underground}', false, false,
   'Address and coords from DICE (venue id 2435), not human-verified. Rooms: Sound Room, The Nursery, Upstairs, Atrium. RA club id not recorded yet.'),
  ('public-records-sound-room', 'Sound Room at Public Records', 'room', '233 Butler St, Brooklyn, NY 11217', '11217', 'Brooklyn', 'Gowanus', null, null,
   null, null, null, null, 200, '{club}', false, 4, '{house.deep,techno.dub}', '{sound_system_focus,intimate_room}', false, false,
   'Main dance room of public-records. Capacity approx.'),
  ('public-records-nursery', 'The Nursery at Public Records', 'room', '233 Butler St, Brooklyn, NY 11217', '11217', 'Brooklyn', 'Gowanus', null, null,
   null, null, null, null, null, '{club,outdoor_yard}', false, 4, '{house.deep,leftfield.downtempo}', '{intimate_room,sunny_day_party}', false, false,
   'Second room / day-party space of public-records.'),
  ('public-records-upstairs', 'Upstairs at Public Records', 'room', '233 Butler St, Brooklyn, NY 11217', '11217', 'Brooklyn', 'Gowanus', null, null,
   null, null, null, null, null, '{bar}', false, 4, '{leftfield.downtempo,jazz.balearic_global}', '{listening_focus,intimate_room}', false, false,
   'Listening bar of public-records.'),
  ('public-records-atrium', 'Atrium at Public Records', 'room', '233 Butler St, Brooklyn, NY 11217', '11217', 'Brooklyn', 'Gowanus', null, null,
   null, null, null, null, null, '{bar}', false, 4, '{open.eclectic}', '{intimate_room}', false, false,
   'Atrium space of public-records.'),
  ('good-room', 'Good Room', 'venue', '98 Meserole Ave, Brooklyn, NY 11222', '11222', 'Brooklyn', 'Greenpoint', null, null,
   'http://www.goodroombk.com', 'goodroombk', 'https://ra.co/clubs/97606', null,
   450, '{club}', false, 3, '{house.deep,house.disco,techno.peak,house.tech}', '{big_room_club,local_crews}', false, false,
   'Address as printed on the venue site (via the goodroom adapter), not human-verified. Capacity approx. Second room: Bad Room. Site is plain-HTTP only (broken TLS).'),
  ('bad-room', 'Bad Room', 'room', '98 Meserole Ave, Brooklyn, NY 11222', '11222', 'Brooklyn', 'Greenpoint', null, null,
   null, null, null, null, null, '{club}', false, 3, '{house.deep,techno.peak}', '{intimate_room}', false, false,
   'Second room of good-room.'),

  -- Brooklyn: standalone venues ----------------------------------------------------------------------------------
  ('signal', 'Signal', 'venue', null, null, 'Brooklyn', 'Bushwick', null, null,
   null, null, 'https://ra.co/clubs/256148', 'https://dice.fm/venue/signal-8ee9w',
   null, '{warehouse,club}', false, 4, '{house.tech,techno.peak,ballroom.vogue,house.disco}', '{dark_warehouse,queer_party,underground}', false, false,
   'Address not on file (new room, 2024/25) — confirm before geocoding. Listings on RA (256148) and DICE (signal-8ee9w).'),
  ('paragon', 'Paragon', 'venue', '1140 Broadway, Brooklyn, NY 11221', '11221', 'Brooklyn', 'Bushwick', null, null,
   'https://www.paragonbroadway.com', null, 'https://ra.co/clubs/195815', 'https://dice.fm/venue/paragon-n958',
   null, '{club,basement}', false, 4, '{techno.peak,house.tech,electro.electro,dnb.jungle}', '{intimate_room,underground,local_crews}', false, false,
   'Website is a landing page; calendar on RA (195815) and DICE (paragon-n958). paragonbk.com is an unrelated business. Address widely published, not human-verified here.'),
  ('bossa-nova-civic-club', 'Bossa Nova Civic Club', 'venue', '1271 Myrtle Ave, Brooklyn, NY 11221', '11221', 'Brooklyn', 'Bushwick', null, null,
   null, 'bossanovacivicclub', 'https://ra.co/clubs/71292', null,
   200, '{club,bar}', false, 5, '{techno.peak,house.jackin,electro.electro,techno.acid}', '{intimate_room,sweaty_basement,underground,local_crews,cheap_early}', false, false,
   'No official website: bossanovacivicclub.com redirects to an unrelated streaming site — never link it. Capacity approx. Address widely published, not human-verified here.'),
  ('mood-ring', 'Mood Ring', 'venue', '1260 Myrtle Ave, Brooklyn, NY 11221', '11221', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null,
   null, '{bar,club}', false, 4, '{open.eclectic,house.disco,bass.club}', '{intimate_room,queer_party,local_crews}', false, false,
   'Address widely published, not human-verified here.'),
  ('jupiter-disco', 'Jupiter Disco', 'venue', '1237 Flushing Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null,
   null, '{bar,club}', false, 4, '{house.deep,techno.dub,electro.electro,leftfield.ambient}', '{intimate_room,free_rsvp,local_crews}', false, false,
   'Usually free entry. Address widely published, not human-verified here.'),
  ('market-hotel', 'Market Hotel', 'venue', '1140 Myrtle Ave, Brooklyn, NY 11221', '11221', 'Brooklyn', 'Bushwick', null, null,
   'https://www.markethotel.org', null, null, null,
   400, '{club,art_space}', false, 4, '{live.indie_electronic,bass.club,techno.peak,open.eclectic}', '{local_crews,underground}', false, false,
   'Capacity approx. Address widely published, not human-verified here.'),
  ('99-scott', '99 Scott', 'venue', '99 Scott Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'East Williamsburg', null, null,
   null, null, null, null,
   null, '{warehouse,art_space,outdoor_yard}', false, 3, '{techno.peak,house.tech,house.afro}', '{dark_warehouse,one_off_special}', false, false,
   'Event space / studio; one-off productions. Address is the name.'),
  ('tba-brooklyn-club', 'TBA Brooklyn', 'venue', '395 Wythe Ave, Brooklyn, NY 11249', '11249', 'Brooklyn', 'Williamsburg', null, null,
   null, null, null, null,
   null, '{bar,club}', false, 3, '{house.tech,house.afro,open.eclectic}', '{intimate_room}', false, true,
   'A real bar/club whose name collides with the "TBA - Brooklyn" placeholder sources use for undisclosed venues. Name-only matches go to the tba-brooklyn sentinel on purpose (alias wins); listings for this room resolve only through a source id. Add its RA club id to venue_external_id when known. Address widely published, not human-verified here.'),
  ('rash', 'Rash', 'venue', '941 Willoughby Ave, Brooklyn, NY 11221', '11221', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null,
   null, '{bar,club}', false, 5, '{techno.hard,electro.electro,bass.club,hard.hardcore}', '{sweaty_basement,intimate_room,queer_party,underground}', false, false,
   'Address widely published, not human-verified here.'),
  ('purgatory', 'Purgatory', 'venue', '675 Central Ave, Brooklyn, NY 11207', '11207', 'Brooklyn', 'Bushwick', null, null,
   null, null, null, null,
   null, '{bar,club}', false, 5, '{open.eclectic,bass.club,electro.ebm_industrial}', '{queer_party,intimate_room,local_crews}', false, false,
   'Address widely published, not human-verified here.'),
  ('the-sultan-room', 'The Sultan Room', 'venue', '234 Starr St, Brooklyn, NY 11237', '11237', 'Brooklyn', 'Bushwick', null, null,
   'https://www.thesultanroom.com', null, null, null,
   null, '{club,rooftop}', false, 3, '{live.indie_electronic,house.disco,latin.latin_bass,open.eclectic}', '{rooftop,local_crews}', false, false,
   'Tickets via DICE and Eventbrite. Address widely published, not human-verified here.'),
  ('mansions', 'Mansions', 'venue', null, null, 'Brooklyn', null, null, null,
   null, null, null, null,
   null, '{club,warehouse}', false, 5, '{techno.peak,house.tech,electro.electro}', '{dark_warehouse,underground,queer_party}', false, false,
   'Address and neighbourhood not on file — confirm before geocoding.'),
  ('brooklyn-army-terminal', 'Brooklyn Army Terminal', 'venue', '140 58th St, Brooklyn, NY 11220', '11220', 'Brooklyn', 'Sunset Park', null, null,
   'http://www.brooklynarmyterminal.com', null, 'https://ra.co/clubs/236259', null,
   null, '{warehouse,outdoor_yard}', false, 2, '{techno.peak,house.tech}', '{big_room_club,festival_scale_lineup,one_off_special,pricey}', false, false,
   'One-off large productions (Teksupport). RA prints "58th St, Brooklyn, NY 11220" and a placeholder location (41, -74) — never copy RA coords for this venue.'),
  ('under-the-k-bridge-park', 'Under the K Bridge Park', 'outdoor', null, null, 'Brooklyn', 'Greenpoint', null, null,
   null, null, null, null,
   null, '{park_or_pier,outdoor_yard}', true, 2, '{techno.peak,house.tech,dubstep.us_bass}', '{park_or_pier,outdoor_yard,festival_scale_lineup,big_room_club}', false, false,
   'Public park under the Kosciuszko Bridge used for large open-air shows. Street address not on file.'),
  ('brooklyn-steel', 'Brooklyn Steel', 'venue', '319 Frost St, Brooklyn, NY 11222', '11222', 'Brooklyn', 'Williamsburg', null, null,
   null, null, null, null,
   1800, '{warehouse,club}', false, 1, '{live.indie_electronic,dubstep.us_bass,techno.peak,dnb.neuro_jumpup}', '{big_room_club,mainstream_club,international_headliner}', false, false,
   'Bowery Presents / Live Nation room; Ticketmaster inventory. Capacity approx. Address widely published, not human-verified here.'),
  ('brooklyn-paramount', 'Brooklyn Paramount', 'venue', '385 Flatbush Ave Ext, Brooklyn, NY 11201', '11201', 'Brooklyn', 'Downtown Brooklyn', null, null,
   null, null, null, null,
   2700, '{club}', false, 1, '{live.indie_electronic,hiphop.rap,dubstep.us_bass}', '{big_room_club,mainstream_club}', false, false,
   'Live Nation theatre; Ticketmaster inventory. Capacity approx. Address widely published, not human-verified here.'),
  ('silo-brooklyn', 'SILO Brooklyn', 'venue', '90 Scott Ave, Brooklyn, NY 11237', '11237', 'Brooklyn', 'East Williamsburg', null, null,
   null, null, null, null,
   null, '{warehouse,club}', false, 3, '{techno.peak,house.tech,trance.prog,house.afro}', '{dark_warehouse,big_room_club,international_headliner}', false, false,
   'Address widely published, not human-verified here. RA/DICE ids not recorded yet.'),
  ('superior-ingredients', 'Superior Ingredients', 'venue', '74 Wythe Ave, Brooklyn, NY 11249', '11249', 'Brooklyn', 'Williamsburg', null, null,
   null, null, null, null,
   null, '{club,rooftop}', false, 2, '{house.tech,techno.peak,house.afro,trance.prog}', '{rooftop,big_room_club}', false, false,
   'Address widely published, not human-verified here.'),
  ('the-lot-radio', 'The Lot Radio', 'venue', '17 Nassau Ave, Brooklyn, NY 11222', '11222', 'Brooklyn', 'Greenpoint', null, null,
   'https://www.thelotradio.com', 'thelotradio', null, null,
   null, '{outdoor_yard,bar}', true, 4, '{house.deep,house.disco,leftfield.downtempo,jazz.brokenbeat}', '{outdoor_yard,sunny_day_party,free_rsvp,local_crews,listening_focus}', false, false,
   'Radio station with a free outdoor yard. Address widely published, not human-verified here.'),
  ('lohi', 'LoHi', 'venue', null, null, 'Brooklyn', null, null, null,
   null, null, null, null,
   null, '{bar,club}', false, 3, '{house.tech,house.afro,open.eclectic}', '{local_crews}', false, false,
   'Address and neighbourhood not on file — confirm before geocoding.'),
  ('green-room-nyc', 'Green Room NYC', 'venue', null, null, null, null, null, null,
   null, null, null, null,
   null, '{club}', false, 2, '{house.tech,techno.peak}', '{}', false, true,
   'Location not on file (borough unknown) — verify before use.'),
  ('babys-all-right', 'Baby''s All Right', 'venue', '146 Broadway, Brooklyn, NY 11211', '11211', 'Brooklyn', 'Williamsburg', null, null,
   'https://babysallright.com', 'babysallright', null, null,
   280, '{club,bar}', false, 3, '{live.indie_electronic,open.eclectic,house.disco}', '{intimate_room,local_crews}', false, false,
   'Tickets via See Tickets US. Mostly live; DJ nights late. Capacity approx. Address widely published, not human-verified here.'),

  -- Manhattan ----------------------------------------------------------------------------------------------------
  ('le-bain', 'Le Bain', 'venue', '848 Washington St, New York, NY 10014', '10014', 'Manhattan', 'Meatpacking District', null, null,
   'https://www.standardhotels.com/new-york/features/le-bain', null, null, null,
   null, '{rooftop,club}', false, 1, '{house.tech,house.disco,open.eclectic}', '{rooftop,mainstream_club}', false, false,
   'Rooftop club of The Standard, High Line. Address widely published, not human-verified here.'),
  ('webster-hall', 'Webster Hall', 'venue', '125 E 11th St, New York, NY 10003', '10003', 'Manhattan', 'East Village', null, null,
   null, null, null, null,
   1500, '{club}', false, 1, '{live.indie_electronic,dubstep.us_bass,hiphop.rap,techno.peak}', '{big_room_club,mainstream_club}', false, false,
   'AEG / AXS ticketing (not Ticketmaster). Capacity approx (Grand Ballroom). Address widely published, not human-verified here.'),
  ('terminal-5', 'Terminal 5', 'venue', '610 W 56th St, New York, NY 10019', '10019', 'Manhattan', 'Hell''s Kitchen', null, null,
   null, null, null, null,
   3000, '{club}', false, 1, '{dubstep.us_bass,trance.prog,techno.peak,dnb.neuro_jumpup}', '{big_room_club,mainstream_club,international_headliner}', false, false,
   'Bowery Presents / Live Nation; Ticketmaster inventory. Capacity approx. Address widely published, not human-verified here.'),

  -- Sentinels: undisclosed venues. kind tba/secret makes venue_sim() neutral and refresh_event() prefer any real room.
  -- Named "Location TBA" so their name_norm never equals a real venue's (see tba-brooklyn-club above).
  ('tba-brooklyn', 'Location TBA – Brooklyn', 'tba', null, null, 'Brooklyn', null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for undisclosed Brooklyn venues ("TBA - Brooklyn" on RA).'),
  ('tba-queens', 'Location TBA – Queens', 'tba', null, null, 'Queens', null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for undisclosed Queens venues.'),
  ('tba-manhattan', 'Location TBA – Manhattan', 'tba', null, null, 'Manhattan', null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for undisclosed Manhattan venues.'),
  ('tba-bronx', 'Location TBA – Bronx', 'tba', null, null, 'Bronx', null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for undisclosed Bronx venues.'),
  ('tba-staten-island', 'Location TBA – Staten Island', 'tba', null, null, 'Staten Island', null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for undisclosed Staten Island venues.'),
  ('tba-new-york', 'Location TBA – New York', 'tba', null, null, null, null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for undisclosed venues with no borough ("TBA - New York" on RA).'),
  ('secret-location', 'Secret Location', 'secret', null, null, null, null, null, null, null, null, null, null,
   null, '{}', null, null, '{}', '{pop_up_secret_location}', false, false, 'Sentinel for events whose venue is revealed to ticket holders only (RA hasSecretVenue, DICE "Secret Location").')
) as s(slug, name, kind, address, postal_code, borough, neighborhood, lat, lng, website, instagram, ra_url, dice_url,
       capacity, space_types, outdoor, underground_prior, typical_genres, vibe_priors, verified, needs_review, notes)
on conflict (slug) do update set
  name = excluded.name, kind = excluded.kind,
  address = coalesce(excluded.address, venue.address), postal_code = coalesce(excluded.postal_code, venue.postal_code),
  borough = coalesce(excluded.borough, venue.borough), neighborhood = coalesce(excluded.neighborhood, venue.neighborhood),
  -- a geocode learned elsewhere beats a null here; a curated coordinate beats a geocode
  lat = coalesce(excluded.lat, venue.lat), lng = coalesce(excluded.lng, venue.lng),
  website = coalesce(excluded.website, venue.website), instagram = coalesce(excluded.instagram, venue.instagram),
  ra_url = coalesce(excluded.ra_url, venue.ra_url), dice_url = coalesce(excluded.dice_url, venue.dice_url),
  capacity = coalesce(excluded.capacity, venue.capacity),
  space_types = excluded.space_types, outdoor = excluded.outdoor, underground_prior = excluded.underground_prior,
  typical_genres = excluded.typical_genres, vibe_priors = excluded.vibe_priors,
  verified = venue.verified or excluded.verified, needs_review = excluded.needs_review, notes = excluded.notes,
  updated_at = now();

------------------------------------------------------------------------------
-- 2. Families: room -> parent (venue_family() rolls rooms up for matching and for the feed's venue label)
------------------------------------------------------------------------------
update venue v set parent_venue_id = p.venue_id, updated_at = now()
from (values
  ('nowadays-yard',             'nowadays'),
  ('knockdown-ruins',           'knockdown-center'),
  ('brooklyn-mirage',           'avant-gardner'),
  ('the-great-hall',            'avant-gardner'),
  ('kings-hall',                'avant-gardner'),
  ('elsewhere-hall',            'elsewhere'),
  ('elsewhere-zone-one',        'elsewhere'),
  ('elsewhere-rooftop',         'elsewhere'),
  ('elsewhere-loft',            'elsewhere'),
  ('public-records-sound-room', 'public-records'),
  ('public-records-nursery',    'public-records'),
  ('public-records-upstairs',   'public-records'),
  ('public-records-atrium',     'public-records'),
  ('bad-room',                  'good-room')
) as r(slug, parent_slug)
join venue p on p.slug = r.parent_slug
where v.slug = r.slug and v.parent_venue_id is distinct from p.venue_id;

------------------------------------------------------------------------------
-- 3. Aliases: every label variant a source prints for these rooms. norm_text() is the key, so case and
--    punctuation do not matter; distinct on the key protects the statement from two spellings colliding.
--    A seeded alias overrides one learned by learn_venue_ref() — curation wins over guesses.
------------------------------------------------------------------------------
insert into venue_alias (alias_norm, alias, venue_id, kind, source_key)
select distinct on (norm_text(a.alias)) norm_text(a.alias), a.alias, v.venue_id, a.kind, a.source_key
from (values
  -- alias, slug, kind, source_key
  ('Nowadays NYC',                       'nowadays',                  'source_label', 'edmtrain'),
  ('Nowadays Ridgewood',                 'nowadays',                  'alias',        null),
  ('Nowadays Bar',                       'nowadays',                  'alias',        null),
  ('The Yard at Nowadays',               'nowadays-yard',             'room',         null),
  ('Nowadays - Yard',                    'nowadays-yard',             'room',         null),
  ('Nowadays (Yard)',                    'nowadays-yard',             'room',         null),
  ('BASEMENT NY',                        'basement',                  'source_label', 'edmtrain'),
  ('Basement NYC',                       'basement',                  'alias',        null),
  ('Basement New York',                  'basement',                  'alias',        null),
  ('Basement Maspeth',                   'basement',                  'alias',        null),
  ('Basement at Knockdown Center',       'basement',                  'alias',        null),
  ('BASEMENT (Knockdown Center)',        'basement',                  'alias',        null),
  ('Knockdown',                          'knockdown-center',          'abbrev',       null),
  ('KDC',                                'knockdown-center',          'abbrev',       null),
  ('The Knockdown Center',               'knockdown-center',          'alias',        null),
  ('Knockdown Center NYC',               'knockdown-center',          'alias',        null),
  ('The Ruins',                          'knockdown-ruins',           'room',         null),
  ('Ruins',                              'knockdown-ruins',           'room',         null),
  ('Knockdown Center Ruins',             'knockdown-ruins',           'room',         null),
  ('Knockdown Center - The Ruins',       'knockdown-ruins',           'room',         null),
  ('The Ruins at Knockdown Center',      'knockdown-ruins',           'room',         'dice'),
  ('MoMA PS1 Courtyard',                 'moma-ps1',                  'alias',        null),
  ('MoMA PS1 Warm Up',                   'moma-ps1',                  'alias',        null),
  ('PS1',                                'moma-ps1',                  'abbrev',       null),
  ('MoMA P.S.1',                         'moma-ps1',                  'former_name',  null),
  ('PS1 Contemporary Art Center',        'moma-ps1',                  'former_name',  null),
  ('HOLO',                               'h0l0',                      'alias',        null),
  ('H0L0 NYC',                           'h0l0',                      'alias',        null),
  ('H0L0 Ridgewood',                     'h0l0',                      'alias',        null),
  ('Trans-Pecos Ridgewood',              'trans-pecos',               'alias',        null),
  ('Trans-Pecos Queens',                 'trans-pecos',               'alias',        null),
  ('TV Eye Ridgewood',                   'tv-eye',                    'alias',        null),
  ('TV Eye NYC',                         'tv-eye',                    'alias',        null),
  ('TVEye',                              'tv-eye',                    'alias',        null),
  -- Avant Gardner family (Pacha New York is the 2026 operator name; RA 286414 / DICE pacha-new-york-6dvb7)
  ('Pacha New York',                     'avant-gardner',             'official',     null),
  ('Pacha NYC',                          'avant-gardner',             'alias',        null),
  ('Pacha Brooklyn',                     'avant-gardner',             'alias',        null),
  ('Brooklyn Pacha',                     'avant-gardner',             'alias',        null),
  ('Avant Gardner Brooklyn',             'avant-gardner',             'alias',        null),
  ('Avant Gardner NYC',                  'avant-gardner',             'alias',        null),
  ('Avant Gardner - The Great Hall',     'the-great-hall',            'room',         null),
  ('Avant Gardner (The Great Hall)',     'the-great-hall',            'room',         null),
  ('Great Hall',                         'the-great-hall',            'room',         null),
  ('The Great Hall at Avant Gardner',    'the-great-hall',            'room',         null),
  ('Pacha New York - The Great Hall',    'the-great-hall',            'room',         null),
  ('Avant Gardner - Kings Hall',         'kings-hall',                'room',         null),
  ('Kings Hall at Avant Gardner',        'kings-hall',                'room',         null),
  ('The Brooklyn Mirage',                'brooklyn-mirage',           'room',         null),
  ('Mirage',                             'brooklyn-mirage',           'room',         null),
  ('Avant Gardner - Brooklyn Mirage',    'brooklyn-mirage',           'room',         null),
  ('Brooklyn Mirage at Avant Gardner',   'brooklyn-mirage',           'room',         null),
  ('The Brooklyn Mirage at Avant Gardner','brooklyn-mirage',          'room',         null),
  -- Elsewhere family (the elsewhere adapter emits "Elsewhere <Room>"; RA/EDMTrain print "Elsewhere - Zone One" etc.)
  ('Elsewhere Brooklyn',                 'elsewhere',                 'alias',        null),
  ('Elsewhere Bushwick',                 'elsewhere',                 'alias',        null),
  ('Elsewhere NYC',                      'elsewhere',                 'alias',        null),
  ('Elsewhere - Full Venue',             'elsewhere',                 'alias',        null),
  ('Elsewhere (Full Venue)',             'elsewhere',                 'alias',        null),
  ('Elsewhere - The Hall',               'elsewhere-hall',            'room',         null),
  ('Elsewhere (The Hall)',               'elsewhere-hall',            'room',         null),
  ('The Hall at Elsewhere',              'elsewhere-hall',            'room',         null),
  ('Elsewhere - Hall',                   'elsewhere-hall',            'room',         null),
  ('Zone One',                           'elsewhere-zone-one',        'room',         null),
  ('Elsewhere - Zone One',               'elsewhere-zone-one',        'room',         null),
  ('Elsewhere (Zone One)',               'elsewhere-zone-one',        'room',         null),
  ('Elsewhere Zone 1',                   'elsewhere-zone-one',        'room',         null),
  ('Zone One at Elsewhere',              'elsewhere-zone-one',        'room',         null),
  ('Elsewhere - Rooftop',                'elsewhere-rooftop',         'room',         null),
  ('Elsewhere (Rooftop)',                'elsewhere-rooftop',         'room',         null),
  ('Elsewhere - The Rooftop',            'elsewhere-rooftop',         'room',         null),
  ('The Rooftop at Elsewhere',           'elsewhere-rooftop',         'room',         null),
  ('Elsewhere - Loft',                   'elsewhere-loft',            'room',         null),
  ('Elsewhere - The Loft',               'elsewhere-loft',            'room',         null),
  ('Elsewhere (The Loft)',               'elsewhere-loft',            'room',         null),
  ('The Loft at Elsewhere',              'elsewhere-loft',            'room',         null),
  -- Public Records family (RA prints the name lower-case; the venue site and DICE name rooms in titles)
  ('public records',                     'public-records',            'source_label', 'ra'),
  ('Public Records NYC',                 'public-records',            'alias',        null),
  ('Public Records Brooklyn',            'public-records',            'alias',        null),
  ('Public Records Gowanus',             'public-records',            'alias',        null),
  ('Sound Room',                         'public-records-sound-room', 'room',         null),
  ('Public Records - Sound Room',        'public-records-sound-room', 'room',         null),
  ('Public Records Sound Room',          'public-records-sound-room', 'room',         null),
  ('Public Records (Sound Room)',        'public-records-sound-room', 'room',         null),
  ('The Nursery',                        'public-records-nursery',    'room',         null),
  ('Public Records - The Nursery',       'public-records-nursery',    'room',         null),
  ('Public Records Nursery',             'public-records-nursery',    'room',         null),
  ('Public Records (The Nursery)',       'public-records-nursery',    'room',         null),
  ('Public Records - Upstairs',          'public-records-upstairs',   'room',         null),
  ('Public Records Upstairs',            'public-records-upstairs',   'room',         null),
  ('Public Records - Atrium',            'public-records-atrium',     'room',         null),
  ('Public Records Atrium',              'public-records-atrium',     'room',         null),
  -- Good Room family
  ('Good Room BK',                       'good-room',                 'alias',        null),
  ('Good Room Brooklyn',                 'good-room',                 'alias',        null),
  ('Good Room Greenpoint',               'good-room',                 'alias',        null),
  ('Goodroom',                           'good-room',                 'alias',        null),
  ('Good Room - Bad Room',               'bad-room',                  'room',         null),
  ('Good Room (Bad Room)',               'bad-room',                  'room',         null),
  ('Bad Room at Good Room',              'bad-room',                  'room',         null),
  -- Brooklyn standalone rooms
  ('Signal Brooklyn',                    'signal',                    'source_label', 'edmtrain'),
  ('Signal Bushwick',                    'signal',                    'alias',        null),
  ('Signal NYC',                         'signal',                    'alias',        null),
  ('Paragon Brooklyn',                   'paragon',                   'alias',        null),
  ('Paragon Broadway',                   'paragon',                   'alias',        null),
  ('Paragon NYC',                        'paragon',                   'alias',        null),
  ('Paragon Bushwick',                   'paragon',                   'alias',        null),
  ('Bossa Nova',                         'bossa-nova-civic-club',     'abbrev',       null),
  ('Bossa',                              'bossa-nova-civic-club',     'abbrev',       null),
  ('BNCC',                               'bossa-nova-civic-club',     'abbrev',       null),
  ('Bossa Nova Civic Club Brooklyn',     'bossa-nova-civic-club',     'alias',        null),
  ('Mood Ring Bar',                      'mood-ring',                 'alias',        null),
  ('Mood Ring Brooklyn',                 'mood-ring',                 'alias',        null),
  ('Jupiter Disco Brooklyn',             'jupiter-disco',             'alias',        null),
  ('Market Hotel Brooklyn',              'market-hotel',              'alias',        null),
  ('Market Hotel Bushwick',              'market-hotel',              'alias',        null),
  ('99 Scott Ave',                       '99-scott',                  'alias',        null),
  ('99 Scott Avenue',                    '99-scott',                  'alias',        null),
  ('99 Scott Studio',                    '99-scott',                  'alias',        null),
  ('Rash Bar',                           'rash',                      'alias',        null),
  ('Rash Brooklyn',                      'rash',                      'alias',        null),
  ('Rash Bushwick',                      'rash',                      'alias',        null),
  ('Purgatory BK',                       'purgatory',                 'alias',        null),
  ('Purgatory Brooklyn',                 'purgatory',                 'alias',        null),
  ('Purgatory Bushwick',                 'purgatory',                 'alias',        null),
  ('Sultan Room',                        'the-sultan-room',           'alias',        null),
  ('The Sultan Room Brooklyn',           'the-sultan-room',           'alias',        null),
  ('Sultan Room Rooftop',                'the-sultan-room',           'alias',        null),
  ('The Sultan Room Rooftop',            'the-sultan-room',           'alias',        null),
  ('Mansions Brooklyn',                  'mansions',                  'alias',        null),
  ('Mansions NYC',                       'mansions',                  'alias',        null),
  ('BAT',                                'brooklyn-army-terminal',    'abbrev',       null),
  ('Brooklyn Army Terminal Annex',       'brooklyn-army-terminal',    'alias',        null),
  ('Brooklyn Army Terminal Pier',        'brooklyn-army-terminal',    'alias',        null),
  ('Under the K Bridge',                 'under-the-k-bridge-park',   'alias',        null),
  ('K Bridge Park',                      'under-the-k-bridge-park',   'alias',        null),
  ('Under the Kosciuszko Bridge',        'under-the-k-bridge-park',   'alias',        null),
  ('Under The K Bridge Park Greenpoint', 'under-the-k-bridge-park',   'alias',        null),
  ('Brooklyn Steel NYC',                 'brooklyn-steel',            'alias',        null),
  ('Brooklyn Paramount Theatre',         'brooklyn-paramount',        'alias',        null),
  ('Paramount Theatre Brooklyn',         'brooklyn-paramount',        'alias',        null),
  ('SILO',                               'silo-brooklyn',             'abbrev',       null),
  ('SILO BK',                            'silo-brooklyn',             'alias',        null),
  ('Silo Brooklyn NYC',                  'silo-brooklyn',             'alias',        null),
  ('Superior Ingredients Rooftop',       'superior-ingredients',      'alias',        null),
  ('Superior Ingredients Brooklyn',      'superior-ingredients',      'alias',        null),
  ('Lot Radio',                          'the-lot-radio',             'alias',        null),
  ('The Lot',                            'the-lot-radio',             'abbrev',       null),
  ('LoHi Brooklyn',                      'lohi',                      'alias',        null),
  ('Lo-Hi',                              'lohi',                      'alias',        null),
  ('Green Room',                         'green-room-nyc',            'alias',        null),
  ('The Green Room NYC',                 'green-room-nyc',            'alias',        null),
  ('Baby''s All Right Brooklyn',         'babys-all-right',           'alias',        null),
  ('Baby''s',                            'babys-all-right',           'abbrev',       null),
  -- Manhattan
  ('Le Bain at The Standard',            'le-bain',                   'alias',        null),
  ('The Standard High Line - Le Bain',   'le-bain',                   'alias',        null),
  ('Le Bain NYC',                        'le-bain',                   'alias',        null),
  ('Le Bain Rooftop',                    'le-bain',                   'alias',        null),
  ('Webster Hall NYC',                   'webster-hall',              'alias',        null),
  ('The Ballroom at Webster Hall',       'webster-hall',              'room',         null),
  ('Webster Hall Ballroom',              'webster-hall',              'room',         null),
  ('Grand Ballroom at Webster Hall',     'webster-hall',              'room',         null),
  ('The Studio at Webster Hall',         'webster-hall',              'room',         null),
  ('Marlin Room at Webster Hall',        'webster-hall',              'room',         null),
  ('Terminal 5 NYC',                     'terminal-5',                'alias',        null),
  ('Terminal Five',                      'terminal-5',                'alias',        null),
  -- Sentinels: how sources spell "we are not telling you yet"
  ('TBA - Brooklyn',                     'tba-brooklyn',              'source_label', 'ra'),
  ('Brooklyn TBA',                       'tba-brooklyn',              'alias',        null),
  ('TBA Venue Brooklyn',                 'tba-brooklyn',              'alias',        null),
  ('Venue TBA Brooklyn',                 'tba-brooklyn',              'alias',        null),
  ('Location TBA Brooklyn',              'tba-brooklyn',              'alias',        null),
  ('Secret Location Brooklyn',           'tba-brooklyn',              'alias',        null),
  ('TBA - Queens',                       'tba-queens',                'source_label', 'ra'),
  ('TBA Queens',                         'tba-queens',                'alias',        null),
  ('Queens TBA',                         'tba-queens',                'alias',        null),
  ('Secret Location Queens',             'tba-queens',                'alias',        null),
  ('TBA - Manhattan',                    'tba-manhattan',             'source_label', 'ra'),
  ('TBA Manhattan',                      'tba-manhattan',             'alias',        null),
  ('Manhattan TBA',                      'tba-manhattan',             'alias',        null),
  ('Secret Location Manhattan',          'tba-manhattan',             'alias',        null),
  ('TBA - Bronx',                        'tba-bronx',                 'source_label', 'ra'),
  ('TBA Bronx',                          'tba-bronx',                 'alias',        null),
  ('TBA - Staten Island',                'tba-staten-island',         'source_label', 'ra'),
  ('TBA Staten Island',                  'tba-staten-island',         'alias',        null),
  ('TBA - New York',                     'tba-new-york',              'source_label', 'ra'),
  ('TBA New York',                       'tba-new-york',              'alias',        null),
  ('TBA NYC',                            'tba-new-york',              'alias',        null),
  ('TBA',                                'tba-new-york',              'alias',        null),
  ('Venue TBA',                          'tba-new-york',              'alias',        null),
  ('Location TBA',                       'tba-new-york',              'alias',        null),
  ('To Be Announced',                    'tba-new-york',              'alias',        null),
  ('Secret Venue',                       'secret-location',           'alias',        null),
  ('Secret Location NYC',                'secret-location',           'alias',        null),
  ('Secret Location New York',           'secret-location',           'alias',        null),
  ('Undisclosed Location',               'secret-location',           'alias',        null)
) as a(alias, slug, kind, source_key)
join venue v on v.slug = a.slug
where norm_text(a.alias) is not null
order by norm_text(a.alias), a.slug
on conflict (alias_norm) do update set
  alias = excluded.alias, venue_id = excluded.venue_id, kind = excluded.kind, source_key = excluded.source_key;

------------------------------------------------------------------------------
-- 4. Source ids (resolve_venue() checks these before any name matching)
------------------------------------------------------------------------------
insert into venue_external_id (source_key, source_id, venue_id)
select x.source_key, x.source_id, v.venue_id
from (values
  ('ra',   '105873', 'nowadays'),
  ('ra',   '165976', 'basement'),
  ('ra',   '69401',  'knockdown-center'),
  ('ra',   '256148', 'signal'),
  ('ra',   '2495',   'moma-ps1'),
  ('ra',   '137550', 'h0l0'),
  ('ra',   '97606',  'good-room'),
  ('ra',   '195815', 'paragon'),
  ('ra',   '71292',  'bossa-nova-civic-club'),
  ('ra',   '105938', 'avant-gardner'),
  ('ra',   '286414', 'avant-gardner'),      -- "Pacha New York" club page -> same family
  ('ra',   '236259', 'brooklyn-army-terminal'),
  ('dice', '2435',   'public-records')      -- numeric DICE venue id; Paragon/Signal/Pacha DICE ids are not known yet (dice_url only)
) as x(source_key, source_id, slug)
join venue v on v.slug = x.slug
on conflict (source_key, source_id) do update set venue_id = excluded.venue_id;
